ltm_pairs:
# Marmac Internal
- name: fn94004-fn94005
  hosts: [fn94004.tmi.telus.com, fn94005.tmi.telus.com]
  env: NP
  dataCenter: Marmac Internal

# Marmac Internal
- name: flute-piccolo
  hosts: [flute.tmi.telus.com, piccolo.tmi.telus.com]
  env: PR
  dataCenter: Marmac Internal

# Laird1 Internal
- name: fn94001-fn94002
  hosts: [fn94001.corp.ads, fn94002.corp.ads]
  env: NP
  dataCenter: Laird1 Internal

# Laird1 Internal
- name: fap0001-fap0002
  hosts: [fap0001.corp.ads, fap0002.corp.ads]
  env: PR
  dataCenter: Laird1 Internal

# Laird2 Internal
- name: fn94012-fn94013
  hosts: [fn94012.corp.ads, fn94013.corp.ads]
  env: NP
  dataCenter: Laird2 Internal

# Laird2 Internal
- name: fp94002-fp94003
  hosts: [fp94002.corp.ads, fp94003.corp.ads]
  env: PR
  dataCenter: Laird2 Internal

# QIDC Internal
- name: btfn000001-btfn000002
  hosts: [btfn000001.tsl.telus.com, btfn000002.tsl.telus.com]
  env: NP
  dataCenter: QIDC Internal

# QIDC Internal
- name: btfp000001-btfp000002
  hosts: [btfp000001.tsl.telus.com, btfp000002.tsl.telus.com]
  env: PR
  dataCenter: QIDC Internal

# KIDC Internal
- name: btfn000010-btfn000011
  hosts: [btfn000010.tsl.telus.com, btfn000011.tsl.telus.com]
  env: NP
  dataCenter: KIDC Internal

# KIDC Internal
- name: btfp000010-btfp000011
  hosts: [btfp000010.tsl.telus.com, btfp000011.tsl.telus.com]
  env: PR
  dataCenter: KIDC Internal

# Toll8 Internal
- name: fp93003-fp93004
  hosts: [fp93003.tsl.telus.com, fp93004.tsl.telus.com]
  env: NP
  dataCenter: Toll8 Internal

# Toll8 Internal
- name: fedm1015-fedm1016
  hosts: [fedm1015.tsl.telus.com, fedm1016.tsl.telus.com]
  env: PR
  dataCenter: Toll8 Internal
