ltm_pairs:
# Marmac Internal
- name: fn94004-fn94005
  hosts: [fn94004.tmi.telus.com, fn94005.tmi.telus.com]
  env: NP
  dataCenter: Marmac Internal

# Marmac Internal
- name: flute-piccolo
  hosts: [flute.tmi.telus.com, piccolo.tmi.telus.com]
  env: PR
  dataCenter: Marmac Internal

# Laird1 Internal
- name: fn94001-fn94002
  hosts: [fn94001.corp.ads, fn94002.corp.ads]
  env: NP
  dataCenter: Laird1 Internal
