server:
  port: 8083
#  ssl:
#    key-store: classpath:keystore/mbonroute.p12
#    key-store-type: PKCS12
#    #    key-alias: tomcat
#    key-store-password: roadside
#    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.241.130/cashier_inventory_product?serverTimezone=EST
    username: root
    password: root
  application:
    name: cashier-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: com/demo/mapper/xml/*.xml

